apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-lab-ingress
  namespace: argocd
spec:
  ingressClassName: traefik
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  - host: localhost
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: wil-playground
            port:
              number: 80